### ISSUE TITLE
atan2

### ISSUE THREAD

**Issue by ericagol** [rodluger/starrynight#1]
Usually arctangent with two entries is written as atan2(sin(\theta),cos(\theta)) = atan2(y,x):

https://github.com/rodluger/starrynight/blob/dfe3f4745ef6ebf71a4c11d877fa698561adedb6/tex/ms.tex#L1779

https://github.com/rodluger/starrynight/blob/dfe3f4745ef6ebf71a4c11d877fa698561adedb6/tex/ms.tex#L2055

https://github.com/rodluger/starrynight/blob/dfe3f4745ef6ebf71a4c11d877fa698561adedb6/tex/ms.tex#L2090

https://github.com/rodluger/starrynight/blob/dfe3f4745ef6ebf71a4c11d877fa698561adedb6/tex/ms.tex#L3103

https://github.com/rodluger/starrynight/blob/dfe3f4745ef6ebf71a4c11d877fa698561adedb6/tex/ms.tex#L3764

https://github.com/rodluger/starrynight/blob/dfe3f4745ef6ebf71a4c11d877fa698561adedb6/tex/ms.tex#L3853

**Comment by rodluger** [comment]
Good point. I *am* actually using that convention. In the first equation, for example,

https://github.com/rodluger/starrynight/blob/dfe3f4745ef6ebf71a4c11d877fa698561adedb6/tex/ms.tex#L1779

the `x_s` and `y_s` arguments aren't the usual `x`, `y` polar coordinates; they are the direction toward the illumination source, which is perpendicular to the major axis of the terminator, from which I measure `theta`. So that introduces a `pi/2` difference in `theta` and the usual polar angle:

```
theta = atan2(y_s, x_s) - pi/2
```

which is equal to

```
-atan2(x_s, y_s)
```

(up to a constant additive factor of `2pi`).

But I suppose I should replace these with my first expression, which is less confusing!

**Comment by ericagol** [comment]
That's good;  just checking that this is what you meant.
