### ISSUE TITLE
Evaluation of equation (C94)

### ISSUE THREAD

**Issue by ericagol** [rodluger/starrynight#2]
I'm wondering if this might benefit from the general elliptic integral introduced in Bulirsch (1969)?

**Comment by rodluger** [comment]
Definitely! Pal's solution is extremely numerically unstable, and mine isn't that much better. But Bulirsch's `el3` is *monstrous*! I didn't think it was worth spending time on that, especially since my numerical evaluation is about as fast as my evaluation of the Carlson RJ term, and a lot more precise.
